"""
LeetCode: Find the Difference
Level: Easy 🟢

Description:
You are given two strings s and t.
String t is generated by random shuffling string s and then adding one more letter 
at a random position. Return the letter that was added to t.

Approach: Hash Map (Counting Frequencies)
Time Complexity: O(n) - Where n is the length of string t.
Space Complexity: O(1) - Since the alphabet size is fixed (26 lowercase English letters).
"""

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        # Count the frequency of characters in both strings
        total_s = Counter(s)
        total_t = Counter(t)

        # Check each character in t to find the mismatch
        for char in total_t:
            if total_t[char] != total_s[char]:
                return char
